export type Language = "sv" | "en" | "da";

export const translations = {
  sv: {
    bookingRequest: "Bokningsförfrågan",
    contactInfo: "Kontaktinformation Huvudresenär",
    name: "Namn",
    departure: "Utresa",
    return: "Hemresa",
    email: "Epost",
    phone: "Telefon",
    customerType: "Välj typ av kund",
    private: "Privatperson",
    business: "Företag",
    peopleCount: "Välj antal personer",
    people2: "2 personer",
    people4: "4 personer",
    people8: "8 personer",
    people12: "12 personer",
    message: "Meddelande",
    playerLevel: "Välj spelarnivå",
    beginner: "Nybörjare(Har spelat 1-4 matcher)",
    amateur: "Amatör(Har spelat 5-10 matcher)",
    hobby: "Motion(Spelar 1-2/Månad)",
    hobbyPlus: "Motion+(Spelar 1/vecka)",
    intermediate: "Medel(Spelar seriespel på en låg/medelnivå)",
    advanced: "Avancerad(Spelar seriespel på en hög nivå)",
    gender: "Kön",
    male: "Man",
    female: "Kvinna",
    unknown: "Vill ej uppge",
    privacyPolicy:
      "Genom att klicka på skicka godkänner jag Premier Padel Travels policy för behandling av personuppgifter.",
    submit: "Skicka",
  },
  en: {
    bookingRequest: "Booking request",
    contactInfo: "Contact information Main traveler",
    name: "Name",
    departure: "Departure",
    return: "Return",
    email: "Email",
    phone: "Phone",
    customerType: "Select customer type",
    private: "Private person",
    business: "Business",
    peopleCount: "Select number of people",
    people2: "2 people",
    people4: "4 people",
    people8: "8 people",
    people12: "12 people",
    message: "Message",
    playerLevel: "Select player level",
    beginner: "Beginner (Played 1-4 matches)",
    amateur: "Amateur (Played 5-10 matches)",
    hobby: "Hobby (Plays 1-2/month)",
    hobbyPlus: "Hobby+ (Plays 1/week)",
    intermediate: "Intermediate (Plays league matches at a low/medium level)",
    advanced: "Advanced (Plays league matches at a high level)",
    gender: "Gender",
    male: "Male",
    female: "Female",
    unknown: "Prefer not to say",
    privacyPolicy:
      "By submitting, I agree to Premier Padel Travels' privacy policy regarding personal data processing.",
    submit: "Submit",
  },
  da: {
    bookingRequest: "Booking anmodning",
    contactInfo: "Kontaktoplysninger Hovedrejsende",
    name: "Navn",
    departure: "Afrejse",
    return: "Retur",
    email: "E-mail",
    phone: "Telefon",
    customerType: "Vælg kundetype",
    private: "Privatperson",
    business: "Virksomhed",
    peopleCount: "Vælg antal personer",
    people2: "2 personer",
    people4: "4 personer",
    people8: "8 personer",
    people12: "12 personer",
    message: "Besked",
    playerLevel: "Vælg spillerniveau",
    beginner: "Begynder (Har spillet 1-4 kampe)",
    amateur: "Amatør (Har spillet 5-10 kampe)",
    hobby: "Motionist (Spiller 1-2/gang pr. måned)",
    hobbyPlus: "Motionist+ (Spiller 1/gang pr. uge)",
    intermediate: "Middel (Spiller seriespil på lav/mellem niveau)",
    advanced: "Avanceret (Spiller seriespil på højt niveau)",
    gender: "Køn",
    male: "Mand",
    female: "Kvinde",
    unknown: "Vil ikke oplyse",
    privacyPolicy:
      "Ved at sende ind, accepterer jeg Premier Padel Travels' privatlivspolitik om behandling af persondata.",
    submit: "Send",
  },
};
